// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	logger "github.com/patrickascher/gofer/logger"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// Log provides a mock function with given fields: _a0
func (_m *Provider) Log(_a0 logger.Entry) {
	_m.Called(_a0)
}
